### ISSUE TITLE
First data column missing

### ISSUE THREAD

**Issue by dmartzc** [stevanusandrianta/breast-cancer-sklearn#1]
Hi Stevan, 

I see that, once the ID column is deleted, you have now 9 features and the 10th that is the result

![image](https://user-images.githubusercontent.com/15961178/33242973-a846dc08-d2a2-11e7-92d4-1d07b0617001.png)

But in your output, when printing the 'data fitur'  you are missing the column 1, which is a feature needed.

The correct way to code it is : 
 `data = dataset.values
x_data = data[:,:9] #Cancer Cell features
y_data = data[:,9]`

and your output will be: 
[[ 5  4  4 ...,  3  2  1]
 [ 3  1  1 ...,  3  1  1]
 [ 6  8  8 ...,  3  7  1]

I really appreciate your colab, keep going!!

Thanks a lot! , Regards
- D. Martinez

**Comment by stevanusandrianta** [comment]
Hi Dmastermx,

Thanks for pointing out my mistake, yes let me fix it
Actually this notebook purpose is creating tutorial in bahasa indonesia, but if you find it helpful, i'll change to english later.

This one is old one, i'm planning to change and cover more material here, so will be much more useful for everyone

**Comment by dmartzc** [comment]
I've found it very useful, thank you so much!

-Regards from Mexico 😊
